---
layout: post
title: "2023-03-28 11:00:00"
subtitle: "ModelData Issues: 0; A-CHAIM System Issues: 8"

---

![]({{ "/assets/img/achaimDataStatsShort-2308711.png" | relative_url }})
![]({{ "/assets/img/achaimDataStatsLong00-2308711.png" | relative_url }})
![]({{ "/assets/img/achaimDataStatsLong01-2308711.png" | relative_url }})
![]({{ "/assets/img/achaimDataStatsLong02-2308711.png" | relative_url }})
![]({{ "/assets/img/modelDataDataStats-2308711.png" | relative_url }})
![]({{ "/assets/img/modelDataStationStats-2308711.png" | relative_url }})
![]({{ "/assets/img/achaimRunTime-2308711.png" | relative_url }})



### A-CHAIM System Issues:  
  
{: .box-error}  
2023-03-28 10:00:13 Unable to read file '/home/chaim/ACHAIM_SERVER/weeklyReports/modelDataPrevErrors.mat'. No such file or directory.  
2023-03-28 10:00:15 Cannot create 'modelDataPrevErrors.mat' because '/home/chaim/ACHAIM_SERVER/weeklyReports' does not exist.  
2023-03-28 10:30:22 RIODECODE:Traceback (most recent call last):
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/readRIO.py", line 3, in <module>
    import go_canada_rio
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/__init__.py", line 1, in <module>
    from riometer import Riometer
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/riometer.py", line 2, in <module>
    from readfiles.raw_data import Raw
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/readfiles/raw_data.py", line 3, in <module>
    import numpy as np
ImportError: No module named numpy
  
2023-03-28 11:00:13 Unable to read file '/home/chaim/ACHAIM_SERVER/weeklyReports/modelDataPrevErrors.mat'. No such file or directory.  
2023-03-28 11:00:15 Cannot create 'modelDataPrevErrors.mat' because '/home/chaim/ACHAIM_SERVER/weeklyReports' does not exist.  
2023-03-28 12:30:11 RIODECODE:Traceback (most recent call last):
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/readRIO.py", line 3, in <module>
    import go_canada_rio
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/__init__.py", line 1, in <module>
    from riometer import Riometer
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/riometer.py", line 2, in <module>
    from readfiles.raw_data import Raw
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/readfiles/raw_data.py", line 3, in <module>
    import numpy as np
ImportError: No module named numpy
  
2023-03-28 13:08:53 Unable to read file '/home/chaim/ACHAIM_SERVER/weeklyReports/modelDataPrevErrors.mat'. No such file or directory.  
2023-03-28 13:30:20 RIODECODE:Traceback (most recent call last):
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/readRIO.py", line 3, in <module>
    import go_canada_rio
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/__init__.py", line 1, in <module>
    from riometer import Riometer
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/riometer.py", line 2, in <module>
    from readfiles.raw_data import Raw
  File "/home/chaim/ACHAIM_SERVER/A-CHAIM/RioPy/go_canada_rio/readfiles/raw_data.py", line 3, in <module>
    import numpy as np
ImportError: No module named numpy
  

### Logs:  
  
{: .box-note}  
[Logs.zip]({{ "/assets/other/logs.zip" | relative_url }})  
[Log Info]({{ "/logInfo" | relative_url }})  
